# Generated by Django 5.1.2 on 2024-10-13 08:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gas_service', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='servicerequest',
            old_name='request',
            new_name='request_text',
        ),
    ]
